# Generated by Django 2.2 on 2020-01-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='memo_text',
            new_name='text',
        ),
    ]
